name: elgomusic
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  smooth_widgets:
    path: /Users/omidshabab/Documents/GitHub/smooth_widgets

  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  iconly: ^1.0.1
  on_audio_query: ^2.9.0
  flutter_svg: ^2.0.6
  just_audio: ^0.9.34
  rxdart: ^0.27.7
  audio_video_progress_bar: ^1.0.1
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.1
  figma_squircle: ^0.5.3
  flutter_staggered_grid_view: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path_android: "assets/images/logo.png"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo-ios.png"

flutter:

  uses-material-design: true

  fonts:
    # PERSIAN
    - family: Estedad
      fonts:
        - asset: assets/fonts/Estedad/Estedad-Thin.ttf
          weight: 100
        - asset: assets/fonts/Estedad/Estedad-Light.ttf
          weight: 200
        - asset: assets/fonts/Estedad/Estedad-ExtraLight.ttf
          weight: 300
        - asset: assets/fonts/Estedad/Estedad-Regular.ttf
          weight: 400
        - asset: assets/fonts/Estedad/Estedad-Medium.ttf
          weight: 500
        - asset: assets/fonts/Estedad/Estedad-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Estedad/Estedad-Bold.ttf
          weight: 700
        - asset: assets/fonts/Estedad/Estedad-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Estedad/Estedad-Black.ttf
          weight: 900

    - family: Rokh
      fonts:
        - asset: assets/fonts/Rokh/RokhFaNum-Light.ttf
          weight: 200
        - asset: assets/fonts/Rokh/RokhFaNum-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rokh/RokhFaNum-Bold.ttf
          weight: 700

    - family: Peyda
      fonts:
        - asset: assets/fonts/Peyda/PeydaFaNum-Regular.ttf
          weight: 400
        - asset: assets/fonts/Peyda/PeydaFaNum-Bold.ttf
          weight: 700


  assets:
    - assets/fonts/
    - assets/images/
    - assets/svg/